# -*- coding: utf-8 -*-
"""ainewsgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zj3NeQkLAs3y8ApEOYciE9DkTS4arCWb
"""

import requests

API_KEY = "4ae008a61a494589b08ca76bc9afa71f"
url = f"https://newsapi.org/v2/top-headlines?country=us&apikey={API_KEY}"

response = requests.get(url)
data = response.json()

articles = data["articles"]

for article in articles[:5]:
    print(article["title"], article["description"])


from transformers import pipeline

summarizer = pipeline(
    "summarization",
    model="sshleifer/distilbart-cnn-12-6"
)

def clean_summary(text):
    # Access 'generated_text' directly from the result of the pipeline for text-generation task
    prompt = f"""
    Summarize this news clearly and professionally in 3-4 sentences.
    Remove repetition and make it easy to read:

    {text}
    """
    return summarizer(prompt[:1000])[0]['summary_text']

html_content = ""

for article in articles:
    summary = clean_summary(article["description"] or article["title"])

    html_content += f"""
    <div style="margin-bottom:20px;">
        <h2 style="color:#2c3e50;">📰 {article['title']}</h2>
        
        <p style="font-size:16px; color:#555;">
            {summary}
        </p>
        
        <a href="{article['url']}" 
           style="color:#1a73e8; font-weight:bold;">
           Read full article →
        </a>
    </div>
    <hr>
    """

import smtplib
from email.mime.text import MIMEText
import os # Make sure os is imported

EMAIL = os.getenv('EMAIL_SENDER') # Get sender email from GitHub secret
PASSWORD = os.getenv('GMAIL_APP_PASSWORD') # Get App Password from GitHub secret

from datetime import datetime

today = datetime.now().strftime("%B %d, %Y")

html_content = f"""
<h1 style="text-align:center;">🧠 Daily News Brief</h1>
<p style="text-align:center; color:gray;">{today}</p>
<hr>
""" + html_content

msg = MIMEText(html_content, "html")
msg["Subject"] = "Daily News Summary"
msg["From"] = EMAIL
msg["To"] = EMAIL

# Use SMTP_SSL for port 465 to establish an SSL-wrapped connection
with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
    server.login(EMAIL, PASSWORD)
    server.send_message(msg)

print("Email sent")
import os

NEWS_API_KEY = os.getenv("NEWS_API_KEY")
EMAIL = os.getenv("EMAIL_SENDER")
PASSWORD = os.getenv("GMAIL_APP_PASSWORD")